name: Ping cURL request

on:
  schedule:
    - cron: '*/15 11-23 * * *'

jobs:
  curl_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: cURl super promo
        run: |
          curl -X GET "vagas1-ik99mzha.b4a.run" \
          -H "Accept: application/json"
