name: Ping cURL request

on:
  schedule:
    - cron: '*/15 10-23 * * *'

jobs:
  curl_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: cURl vagas
        run: |
          curl -X GET "https://vagas1-ik99mzha.b4a.run/" \
          -H "Accept: application/json"

  curl_request_puppeteer:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: cURl vagas
        run: |
          curl -X GET "https://pupperter-promo-1.onrender.com/" \
          -H "Accept: application/json"
