name: Ping cURL request

on:
  schedule:
    - cron: '*/15 10-23 * * *'

jobs:
  curl_request_bots:
    runs-on: ubuntu-latest
    
    steps:
      - name: cURl vagas
        run: |
          curl -X GET "https://vagas-5l0y.onrender.com" \
          -H "Accept: application/json"

      - name: cURl puppeter-promo
        run: |
          curl -X GET "https://pupperter-promo-1.onrender.com/" \
          -H "Accept: application/json"

      - name: cURl super-promo
        run: |
          curl -X GET "https://superpromoamazon-pr1k524z.b4a.run/" \
          -H "Accept: application/json"

