name: Ping cURL request

on:
  schedule:
    - cron: '*/15 10-23 * * *'

jobs:
  curl_request_vagas:
    runs-on: ubuntu-latest
    
    steps:
      - name: cURl vagas
        run: |
          curl -X GET "https://padrinhovagas3-zmwydi5g.b4a.run/" \
          -H "Accept: application/json"

      - name: cURl padrinho
        run: |
          curl -X GET "https://gemini-integration-api.onrender.com/ping/" \
          -H "Accept: application/json"

