name: Ping cURL request

on:
  schedule:
    - cron: '*/15 10-23 * * *'

jobs:
  curl_request_vagas:
    runs-on: ubuntu-latest
    
    steps:
      - name: cURl vagas
        run: |
          curl -X GET "https://vagas-bot.onrender.com" \
          -H "Accept: application/json"

